apiVersion: v1 # creating the real storage and add it to local-sc sttorag CLASS
kind: PersistentVolume
metadata:
    name: ftps-pv
spec:
    storageClassName: local-sc
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ft_service/FTPS"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ftps-pvc
spec:
    storageClassName: local-sc
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps-depl-name
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ftps-ptr
    template:
        metadata:
            labels:
                app: ftps-ptr
        spec:
            volumes:
                - name: ftps-volume
                  persistentVolumeClaim: 
                    claimName: ftps-pvc
            containers:
              - name: ftps-con
                image: my-ftps
                imagePullPolicy: Never
                volumeMounts:
                  - mountPath: "/home/mohamed/"
                    name: ftps-volume
                ports:
                    - containerPort: 21
                    - containerPort: 20
                    - containerPort: 30020
                    - containerPort: 30021
---
apiVersion: v1
kind: Service
metadata:
      name: ftps-alpine
      labels:
        run: ftps-alpine
spec:
      type: LoadBalancer
      ports:
      - port: 21
        targetPort: 21
        name: ftp-ctl
      - port: 20
        targetPort: 20
        name: ftp-data
      - port: 30020
        targetPort: 30020
        name: ftp-r1
      - port: 30021
        targetPort: 30021
        name: ftp-r2
      selector:
        app: ftps-ptr
