apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            mysql-ptr: mysql-ptr
    template:
        metadata:
            labels:
                mysql-ptr: mysql-ptr
        spec:
            containers:
                - name: mysql-con
                  image: mysql
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
spec:
    selector:
        mysql-ptr: mysql-ptr
    ports:
      - port: 8888
        targetPort: 8080

